  services:
    db:
      image: postgres:15-alpine
      env_file:
        - .env
      ports:
        - "5432:5432" 
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - flight-network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        timeout: 10s
        retries: 3
    
    flight-service:
      build: 
        context: ./flight-service
        dockerfile: Dockerfile
      depends_on:
        db:
          condition: service_healthy
      ports:
        - "6001:6001"
      env_file:
        - ./flight-service/.env
      networks:
        - flight-network
      restart: on-failure
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:6001"]
        interval: 10s
        timeout: 5s
        retries: 3

    flight-booking:
      build: 
        context: ./flight-booking
        dockerfile: Dockerfile
      depends_on:
        - flight-service
      ports:
        - "6000:6000"
      env_file:
        - ./flight-booking/.env
      networks:
        - flight-network
      restart: on-failure
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:6000/api/v1/info"]
        interval: 10s
        timeout: 5s
        retries: 3

    gateway:
      build: 
        context: ./gateway
        dockerfile: Dockerfile
      depends_on:
        db:
          condition: service_healthy
      restart: always
      networks:
        - flight-network
      ports:
        - "6003:6003"
      env_file:
        - ./gateway/.env



  volumes:
    postgres_data:
  networks:
    flight-network: